import { degrees, rgb, StandardFonts, type PDFDocument, type PDFPage } from 'pdf-lib';
import { mmToPt } from './units';

const FOOTER_TEXT = 'Print at 100% / Actual Size — do not scale to fit. Generated by PrintReady.';

/** Adds the bottom-edge note required on every PrintReady output. */
export async function drawFooterNote(pdf: PDFDocument, page: PDFPage) {
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontSize = 6;
  const text = FOOTER_TEXT;
  const textWidth = font.widthOfTextAtSize(text, fontSize);
  const { width } = page.getSize();
  page.drawText(text, {
    x: (width - textWidth) / 2,
    y: mmToPt(2),
    size: fontSize,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });
}

/** Draws a diagonal watermark across the page (Silver-tier output). */
export async function drawWatermark(pdf: PDFDocument, page: PDFPage, text: string) {
  const font = await pdf.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();
  const fontSize = 48;
  const textWidth = font.widthOfTextAtSize(text, fontSize);
  page.drawText(text, {
    x: (width - textWidth) / 2,
    y: height / 2,
    size: fontSize,
    font,
    color: rgb(0.85, 0.85, 0.85),
    rotate: degrees(-30),
    opacity: 0.35,
  });
}
